### ISSUE TITLE
Startup crash on server

### ISSUE THREAD

**Issue by ShadowedSong** [RedstoneParadox/TinkersArsenal#10]
Mantle version: Mantle-1.12-1.3.2.24
Tinkers' Construct version: TConstruct-1.12.2-2.10.1.87
Tinkers' Arsenal version: tinkersarsenal-0.4

Versions of other mods required to replicate the issue:
RedstoneFlux-1.12-2.0.2.3-universal
CoFHWorld-1.12.2-1.2.0.5-universal
CoFHCore-1.12.2-4.5.3.20-universal

What happened (BE DESCRIPTIVE!!!):
server crashes in less than a minute
crash report
https://pastebin.com/nkecY8Y7

log
https://pastebin.com/jkzCVp0R

**Comment by RedstoneParadox** [comment]
Jsyk, this has nothing to do with the CoFH mods or RedstoneFlux; please only list other mods if you cannot replicate the issue without those mods.

**Comment by MrNoaaan** [comment]
I just got a similar crashlog, only that i was using other mods -CoFHWorld.
This is most likely due to the new Forge update. For now you could try using an older version of Forge and the mods to see if it still works.

**Comment by MrNoaaan** [comment]
Here is a crash log for the latest/recommended Forge build with Tinkers Arsenal and it's required libraries.
[crash-2018-10-07_16.46.52-server.txt](https://github.com/RedstoneParadox/TinkersArsenal/files/2454008/crash-2018-10-07_16.46.52-server.txt)

**Comment by RedstoneParadox** [comment]
Locking this as I have already figured out the issue.

**Comment by RedstoneParadox** [comment]
Fixed in next release.
